# Generated by Django 4.2.7 on 2023-11-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netapi', '0002_alter_serverinfo_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
